name: diana_xml_ct
description: Enable xml content type in diana framework.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  diana:
    path: ../diana
  xml: ^6.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
